language: minimal
os: linux
arch: amd64
script:
- wget https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
- gzip -d ow-snapshot.tar.gz
- mkdir _watcom
- cd _watcom
- tar -xf ../ow-snapshot.tar
- cd ..
- export PATH=$TRAVIS_BUILD_DIR/bin:$PATH:$TRAVIS_BUILD_DIR/_watcom/binl64
- export WATCOM=$TRAVIS_BUILD_DIR/_watcom
- export ROOT_DIR=$TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR/Tools/pmake/pmake
- wmake install
- cd $TRAVIS_BUILD_DIR/Installed/Tools
- pmake install
- cd $TRAVIS_BUILD_DIR/Installed
- pmake | tee $TRAVIS_BUILD_DIR/_build.log | grep "\-\-\- "
- cd $TRAVIS_BUILD_DIR/Tools/build/product/bbxensem/Scripts
- echo pc >$TRAVIS_BUILD_DIR/_temp.dat
- echo y >>$TRAVIS_BUILD_DIR/_temp.dat
- echo n >>$TRAVIS_BUILD_DIR/_temp.dat
- echo y >>$TRAVIS_BUILD_DIR/_temp.dat
- echo n >>$TRAVIS_BUILD_DIR/_temp.dat
- echo $TRAVIS_BUILD_DIR/_out >> $TRAVIS_BUILD_DIR/_temp.dat
- perl -I. buildbbx.pl  <$TRAVIS_BUILD_DIR/_temp.dat

