language: minimal
os: linux
script:
- wget https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
- gzip -d ow-snapshot.tar.gz
- mkdir _watcom
- cd _watcom
- tar -xf ../ow-snapshot.tar
- cd ..
- export PATH=$PATH:$TRAVIS_BUILD_DIR/_watcom/binl64:$TRAVIS_BUILD_DIR/bin
- export WATCOM=$TRAVIS_BUILD_DIR/_watcom
- export ROOT_DIR=$TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR/Tools/pmake/pmake
- wmake install
- cd $TRAVIS_BUILD_DIR/Installed/Tools
- pmake install
- cd $TRAVIS_BUILD_DIR/Installed
- pmake

