language: minimal
os: linux
script:
- wget https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
- gzip -d ow-snapshot.tar.gz
- tar -xf ow-snapshot.tar
- ow-snapshot/binl64/wcc
- cd $TRAVIS_BUILD_DIR/Tools/pmake/pmake
- wmake
