language: minimal
os: linux
script:
- wget https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/open-watcom-2_0-c-linux-x64
- sudo ./open-watcom-2_0-c-linux-x64
- cd $TRAVIS_BUILD_DIR/Tools/pmake/pmake
- wmake
